In [7]:
!pip install playwright pandas
!playwright install

Collecting playwright
  Downloading playwright-1.58.0-py3-none-macosx_11_0_arm64.whl.metadata (3.5 kB)
Requirement already satisfied: pandas in ./miniforge3/lib/python3.12/site-packages (2.2.0)
Collecting pyee<14,>=13 (from playwright)
  Downloading pyee-13.0.1-py3-none-any.whl.metadata (3.0 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright)
  Downloading greenlet-3.3.2-cp312-cp312-macosx_11_0_universal2.whl.metadata (3.7 kB)
Requirement already satisfied: typing-extensions in ./miniforge3/lib/python3.12/site-packages (from pyee<14,>=13->playwright) (4.15.0)
Requirement already satisfied: numpy<2,>=1.26.0 in ./miniforge3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniforge3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./miniforge3/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./miniforge3/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./miniforge3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading playwright-1.58.0-py3-none-macosx_11_0_arm64.whl (41.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 MB 1.7 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading greenlet-3.3.2-cp312-cp312-macosx_11_0_universal2.whl (280 kB)
Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Installing collected packages: pyee, greenlet, playwright
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [playwright]━━━━━━━ 2/3 [playwright]
Successfully installed greenlet-3.3.2 playwright-1.58.0 pyee-13.0.1
Downloading Chrome for Testing 145.0.7632.6 (playwright chromium v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/mac-arm64/chrome-mac-arm64.zip
(node:47287) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)

In [3]:
!playwright install chromium

Downloading Chrome for Testing 145.0.7632.6 (playwright chromium v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/mac-arm64/chrome-mac-arm64.zip
(node:33003) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)

In [11]:
from playwright.async_api import async_playwright
import asyncio
import json
import os
from datetime import datetime, timedelta

# --- CONFIGURATION ---
X_AUTH_TOKEN = "8b93f87f79151190d91e281eb76d10542685c500" # <-- Put a fresh token here! Keep it secret.

BASE_QUERY = "from:PIBFactCheck (bank OR RBI OR SBI OR finance OR loan OR tax OR fraud OR scam OR rupees OR UPI OR investment OR mutual) filter:media"

# Hardcode your absolute start and end dates here. 
# The script will ignore DEFAULT_START_DATE if a checkpoint exists.
DEFAULT_START_DATE = datetime(2023, 1, 1) 
END_DATE = datetime(2026, 4, 8)
CHUNK_DAYS = 30 
CHECKPOINT_FILE = "scraper_checkpoint.txt"
JSON_FILE = "raw_tweets_bulk.json"

def get_start_date():
    """Reads the last successful date from the checkpoint file, if it exists."""
    if os.path.exists(CHECKPOINT_FILE):
        with open(CHECKPOINT_FILE, "r") as f:
            saved_date = f.read().strip()
            if saved_date:
                print(f"🔄 Checkpoint found! Resuming from: {saved_date}")
                return datetime.strptime(saved_date, "%Y-%m-%d")
    
    print(f"▶️ No checkpoint found. Starting from default: {DEFAULT_START_DATE.strftime('%Y-%m-%d')}")
    return DEFAULT_START_DATE

def get_date_ranges(start_date):
    ranges = []
    current = start_date
    while current < END_DATE:
        next_date = current + timedelta(days=CHUNK_DAYS)
        if next_date > END_DATE:
            next_date = END_DATE
        ranges.append((current.strftime("%Y-%m-%d"), next_date.strftime("%Y-%m-%d")))
        current = next_date
    return ranges

async def run_scraper():
    scraped_data = []
    seen_tweets = set()
    
    # Load existing data to append
    if os.path.exists(JSON_FILE):
        with open(JSON_FILE, "r", encoding="utf-8") as f:
            try:
                scraped_data = json.load(f)
                seen_tweets = {item["image_url"] for item in scraped_data}
                print(f"📦 Loaded {len(scraped_data)} previously scraped tweets.")
            except json.JSONDecodeError:
                pass

    # Figure out where to start based on checkpoints
    actual_start_date = get_start_date()
    date_ranges = get_date_ranges(actual_start_date)
    
    if not date_ranges:
        print("✅ End date reached. Nothing left to scrape!")
        return scraped_data

    print(f"Generated {len(date_ranges)} timeboxed searches to execute...")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=False,
            args=["--disable-blink-features=AutomationControlled"]
        )
        
        context = await browser.new_context(
            viewport={"width": 1280, "height": 900},
            user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
        )
        
        await context.add_cookies([{"name": "auth_token", "value": X_AUTH_TOKEN, "domain": ".x.com", "path": "/"}])
        page = await context.new_page()

        for since_date, until_date in date_ranges:
            url_query = f"{BASE_QUERY} since:{since_date} until:{until_date}"
            search_url = f"https://x.com/search?q={url_query}&src=typed_query"
            
            print(f"\n🗓️ Searching: {since_date} to {until_date}...")
            
            max_retries = 3
            attempt = 0
            chunk_success = False

            while attempt < max_retries and not chunk_success:
                attempt += 1
                try:
                    await page.goto(search_url, timeout=60000, wait_until="domcontentloaded")
                    await asyncio.sleep(3) # Give the page a moment to decide what to render
                except Exception:
                    print(f"  -> ⚠️ Navigation timed out or failed (Attempt {attempt}). Retrying...")
                    await asyncio.sleep(5)
                    continue
                
                # 1. Check if X threw the rate-limit/error page
                error_loc = page.locator('text="Something went wrong"')
                retry_btn = page.locator('[data-testid="empty_state_button_text"]')
                
                if await error_loc.count() > 0 or await retry_btn.count() > 0:
                    wait_time = 60 * attempt # Wait 1 min, then 2 mins, etc.
                    print(f"  -> 🛑 X blocked the request. Cooling down for {wait_time} seconds...")
                    await asyncio.sleep(wait_time)
                    continue # Loop restarts, trying the same date range again

                # 2. If no error, wait for tweets
                try:
                    await page.wait_for_selector('[data-testid="tweet"]', timeout=8000)
                    chunk_success = True # We found the page successfully
                except Exception:
                    # Double check it isn't an error page we missed before assuming empty
                    if await page.locator('text="Something went wrong"').count() == 0:
                        print("  -> No tweets found for this time period.")
                        chunk_success = True # Successfully determined it's empty
                    continue

                # 3. Extraction Logic
                if chunk_success:
                    for _ in range(2): 
                        tweets = await page.locator('[data-testid="tweet"]').all()
                        for tweet in tweets:
                            try:
                                text_loc = tweet.locator('[data-testid="tweetText"]')
                                tweet_text = await text_loc.inner_text() if await text_loc.count() > 0 else ""
                                
                                photo_loc = tweet.locator('[data-testid="tweetPhoto"] img')
                                if await photo_loc.count() > 0:
                                    image_url = await photo_loc.first.get_attribute('src')
                                    
                                    tweet_url = ""
                                    time_link = tweet.locator('a:has(time)')
                                    if await time_link.count() > 0:
                                        href = await time_link.first.get_attribute('href')
                                        if href:
                                            tweet_url = f"https://x.com{href}"
                                    
                                    if image_url and "media" in image_url and image_url not in seen_tweets:
                                        seen_tweets.add(image_url)
                                        scraped_data.append({
                                            "tweet_text": tweet_text,
                                            "image_url": image_url,
                                            "tweet_url": tweet_url
                                        })
                                        print(f"  ✅ [Total: {len(seen_tweets)}] Extracted: {tweet_text[:30].replace(chr(10), ' ')}...")
                            except Exception:
                                continue
                        
                        await page.mouse.wheel(0, 2000)
                        await asyncio.sleep(2)

            if not chunk_success:
                print(f"  -> ❌ Failed to fetch {since_date} to {until_date} after {max_retries} attempts. Stopping script to prevent ban.")
                break # Stop the entire script so you don't burn your account

            # --- THE CHECKPOINT SYSTEM ---
            with open(JSON_FILE, "w", encoding="utf-8") as f:
                json.dump(scraped_data, f, indent=4)
            
            with open(CHECKPOINT_FILE, "w") as f:
                f.write(until_date)
            # -----------------------------

        await context.close()
        await browser.close()
        
    return scraped_data

# Run it!
if __name__ == "__main__":
    # In Jupyter, just await the function directly!
    data = await run_scraper()
    
    print(f"\n🎉 BOOM. Run complete. Total dataset now has {len(data)} tweets.")

📦 Loaded 9 previously scraped tweets.
🔄 Checkpoint found! Resuming from: 2023-08-29
Generated 32 timeboxed searches to execute...

🗓️ Searching: 2023-08-29 to 2023-09-28...
  ✅ [Total: 10] Extracted: An approval letter claims to g...
  ✅ [Total: 11] Extracted: An e-mail allegedly sent by RB...
  ✅ [Total: 12] Extracted: Claim: The customer's India Po...

🗓️ Searching: 2023-09-28 to 2023-10-28...
  ✅ [Total: 13] Extracted: A viral message circulating on...
  ✅ [Total: 14] Extracted: A Press Release, dated 25 Octo...
  ✅ [Total: 15] Extracted: A receipt allegedly issued by ...

🗓️ Searching: 2023-10-28 to 2023-11-27...
  ✅ [Total: 16] Extracted: Claim: The customer's India Po...
  ✅ [Total: 17] Extracted: A bogus lucky draw allegedly f...
  ✅ [Total: 18] Extracted: People have received notices f...

🗓️ Searching: 2023-11-27 to 2023-12-27...
  ✅ [Total: 19] Extracted: It is claimed that the Prime M...
  ✅ [Total: 20] Extracted: In a video, it has been claime...
  ✅ [Total: 21] Extracted: It is claimed in a video that ...
  ✅ [Total: 22] Extracted: Do you have a ₹500 note with a...
  ✅ [Total: 23] Extracted: In the video, it is claimed th...

🗓️ Searching: 2023-12-27 to 2024-01-26...
  ✅ [Total: 24] Extracted: A #Fake approval letter claims...
  ✅ [Total: 25] Extracted: People have received notices f...
  ✅ [Total: 26] Extracted: Claim: The customer's India Po...
  ✅ [Total: 27] Extracted: An approval letter claims to g...
  ✅ [Total: 28] Extracted: Do you have a ₹500 note with a...
  ✅ [Total: 29] Extracted: A viral message claims that th...

🗓️ Searching: 2024-01-26 to 2024-02-25...
  ✅ [Total: 30] Extracted: An image circulating on social...
  ✅ [Total: 31] Extracted: People have received notices f...
  ✅ [Total: 32] Extracted: A viral message on social medi...

🗓️ Searching: 2024-02-25 to 2024-03-26...
  ✅ [Total: 33] Extracted: A post falsely attributed to  ...
  ✅ [Total: 34] Extracted: A #FAKE lucky draw in the name...
  ✅ [Total: 35] Extracted: Have you recently received any...

🗓️ Searching: 2024-03-26 to 2024-04-25...
  ✅ [Total: 36] Extracted: दावा:  @RBI  ने आधार बैंकिंग म...
  ✅ [Total: 37] Extracted: Don't get zapped by this scam!...
  ✅ [Total: 38] Extracted: A #WhatsApp message with a lin...
  ✅ [Total: 39] Extracted: Received an e-mail informing y...

🗓️ Searching: 2024-04-25 to 2024-05-25...
  ✅ [Total: 40] Extracted: सोशल मीडिया पर शेयर किए जा रहे...

🗓️ Searching: 2024-05-25 to 2024-06-24...
  ✅ [Total: 41] Extracted: The thumbnail of a #YouTube ch...

🗓️ Searching: 2024-06-24 to 2024-07-24...
  ✅ [Total: 42] Extracted: A #fake approval letter allege...
  ✅ [Total: 43] Extracted: Do you have a ₹500 note with a...
  ✅ [Total: 44] Extracted: Have you recently received any...

🗓️ Searching: 2024-07-24 to 2024-08-23...
  ✅ [Total: 45] Extracted: Claim: The customer's India Po...
  ✅ [Total: 46] Extracted:  Fake News Alert  कुछ आर्टिकल ...
  ✅ [Total: 47] Extracted: Posts on Social Media misinter...
  ✅ [Total: 48] Extracted: Do you have a ₹500 note with a...
  ✅ [Total: 49] Extracted: Beware   Did you also receive ...

🗓️ Searching: 2024-08-23 to 2024-09-22...
  ✅ [Total: 50] Extracted: Did you also receive a #WhatsA...
  ✅ [Total: 51] Extracted: An approval letter claims to g...
  ✅ [Total: 52] Extracted: दावा:  @RBI  ने आधार बैंकिंग म...
  ✅ [Total: 53] Extracted: Have you recently received any...
  ✅ [Total: 54] Extracted: A #WhatsApp message with a lin...
  ✅ [Total: 55] Extracted: A #WhatsApp message with a lin...

🗓️ Searching: 2024-09-22 to 2024-10-22...
  ✅ [Total: 56] Extracted: Do you have a ₹500 note with a...
  ✅ [Total: 57] Extracted: A post falsely attributed to  ...
  ✅ [Total: 58] Extracted: A message with a link claims t...
  ✅ [Total: 59] Extracted: Received an e-mail informing y...
  ✅ [Total: 60] Extracted: Don't get zapped by this scam!...

🗓️ Searching: 2024-10-22 to 2024-11-21...
  ✅ [Total: 61] Extracted: Beware   Did you also receive ...
  ✅ [Total: 62] Extracted: Did you also receive a #WhatsA...
  ✅ [Total: 63] Extracted: Have you recently received any...
  ✅ [Total: 64] Extracted: A #fake approval letter allege...

🗓️ Searching: 2024-11-21 to 2024-12-21...
  ✅ [Total: 65] Extracted: An interview of RBI Governor S...
  ✅ [Total: 66] Extracted: A blogspot " https:// blog.sag...
  ✅ [Total: 67] Extracted: A #WhatsApp message with a lin...
  ✅ [Total: 68] Extracted: A #Fake approval letter claims...
  ✅ [Total: 69] Extracted:  Fake News Alert  कुछ आर्टिकल ...
  ✅ [Total: 70] Extracted: Have you recently received any...

🗓️ Searching: 2024-12-21 to 2025-01-20...
  ✅ [Total: 71] Extracted: सतर्क रहें   सोशल मीडिया पर दा...
  ✅ [Total: 72] Extracted: Received an e-mail informing y...
  ✅ [Total: 73] Extracted: Have you received a voicemail,...
  ✅ [Total: 74] Extracted: A #fake approval letter allege...
  ✅ [Total: 75] Extracted: Beware   Did you also receive ...
  ✅ [Total: 76] Extracted: A #fake lucky draw is luring p...

🗓️ Searching: 2025-01-20 to 2025-02-19...
  ✅ [Total: 77] Extracted: Have you recently received any...
  ✅ [Total: 78] Extracted: SCAM Alert   An advertisement ...
  ✅ [Total: 79] Extracted: A #Fake approval letter claims...
  ✅ [Total: 80] Extracted: A #fake lucky draw is luring p...
  ✅ [Total: 81] Extracted: Claim: The customer's India Po...

🗓️ Searching: 2025-02-19 to 2025-03-21...
  ✅ [Total: 82] Extracted: A news report by Lokmat Times ...
  ✅ [Total: 83] Extracted: A #fake approval letter allege...
  ✅ [Total: 84] Extracted: A #fake lucky draw is luring p...
  ✅ [Total: 85] Extracted: Do you have a ₹500 note with a...
  ✅ [Total: 86] Extracted: Received an e-mail informing y...
  ✅ [Total: 87] Extracted: A #WhatsApp message with a lin...

🗓️ Searching: 2025-03-21 to 2025-04-20...
  ✅ [Total: 88] Extracted:  Scam alert !!   Have you rece...
  ✅ [Total: 89] Extracted: A #fake approval letter allege...
  ✅ [Total: 90] Extracted: A #fake lucky draw is luring p...
  ✅ [Total: 91] Extracted: Received an e-mail regarding a...
  ✅ [Total: 92] Extracted: It is being claimed in social ...
  ✅ [Total: 93] Extracted:  Alert: Fake YouTube Thumbnail...

🗓️ Searching: 2025-04-20 to 2025-05-20...
  ✅ [Total: 94] Extracted: Several posts on social media ...
  ✅ [Total: 95] Extracted: A post falsely attributed to  ...
  ✅ [Total: 96] Extracted: Beware    Did you also receive...
  ✅ [Total: 97] Extracted: A WhatsApp message is going ar...

🗓️ Searching: 2025-05-20 to 2025-06-19...
  ✅ [Total: 98] Extracted: A video on social media shows ...
  ✅ [Total: 99] Extracted: A video circulating on social ...
  ✅ [Total: 100] Extracted: Beware   Did you also receive ...
  ✅ [Total: 101] Extracted: A WhatsApp message is going ar...
  ✅ [Total: 102] Extracted: Have you received a voicemail,...
  ✅ [Total: 103] Extracted: A message circulating on Whats...
  ✅ [Total: 104] Extracted: A #Fake approval letter claims...

🗓️ Searching: 2025-06-19 to 2025-07-19...
  ✅ [Total: 105] Extracted: "Chance to win a Fuel Subsidy ...
  ✅ [Total: 106] Extracted:  PM Modi promoting an investme...
  ✅ [Total: 107] Extracted: Just click on the link & share...
  ✅ [Total: 108] Extracted: Has RBI really asked banks to ...
  ✅ [Total: 109] Extracted: Have you recently received any...
  ✅ [Total: 110] Extracted: Did you also receive a message...

🗓️ Searching: 2025-07-19 to 2025-08-18...
  ✅ [Total: 111] Extracted:  Scam alert !!   Have you rece...
  ✅ [Total: 112] Extracted: Has India really introduced 'Q...
  ✅ [Total: 113] Extracted: Do you have a ₹500 note with a...

🗓️ Searching: 2025-08-18 to 2025-09-17...
  -> No tweets found for this time period.

🗓️ Searching: 2025-09-17 to 2025-10-17...
  -> No tweets found for this time period.

🗓️ Searching: 2025-10-17 to 2025-11-16...
  -> No tweets found for this time period.

🗓️ Searching: 2025-11-16 to 2025-12-16...
  -> No tweets found for this time period.

🗓️ Searching: 2025-12-16 to 2026-01-15...
  -> No tweets found for this time period.

🗓️ Searching: 2026-01-15 to 2026-02-14...
  -> No tweets found for this time period.

🗓️ Searching: 2026-02-14 to 2026-03-16...
  -> No tweets found for this time period.

🗓️ Searching: 2026-03-16 to 2026-04-08...
  -> No tweets found for this time period.

🎉 BOOM. Run complete. Total dataset now has 113 tweets.

In [12]:
from playwright.async_api import async_playwright
import asyncio
import json
import os
from datetime import datetime, timedelta

# --- RECOVERY CONFIGURATION ---
X_AUTH_TOKEN = "8b93f87f79151190d91e281eb76d10542685c500" # <-- Put your token here (Use a fresh one if the current one is soft-banned!)
BASE_QUERY = "from:PIBFactCheck (bank OR RBI OR SBI OR finance OR loan OR tax OR fraud OR scam OR rupees OR UPI OR investment OR mutual) filter:media"

# Hardcoding the exact period where the soft-ban started
RECOVERY_START = datetime(2025, 8, 18) 
RECOVERY_END = datetime(2026, 4, 8)
CHUNK_DAYS = 30 
JSON_FILE = "raw_tweets_bulk.json"

def get_recovery_ranges():
    ranges = []
    current = RECOVERY_START
    while current < RECOVERY_END:
        next_date = current + timedelta(days=CHUNK_DAYS)
        if next_date > RECOVERY_END:
            next_date = RECOVERY_END
        ranges.append((current.strftime("%Y-%m-%d"), next_date.strftime("%Y-%m-%d")))
        current = next_date
    return ranges

async def run_recovery_scraper():
    scraped_data = []
    seen_tweets = set()
    
    # 1. Load the 113 existing tweets to prevent overwriting/duplicates
    if os.path.exists(JSON_FILE):
        with open(JSON_FILE, "r", encoding="utf-8") as f:
            try:
                scraped_data = json.load(f)
                seen_tweets = {item["image_url"] for item in scraped_data}
                print(f"📦 Loaded {len(scraped_data)} previously scraped tweets. Ready to append...")
            except json.JSONDecodeError:
                print("⚠️ Could not read existing JSON. Starting fresh.")

    date_ranges = get_recovery_ranges()
    print(f"Generated {len(date_ranges)} recovery timeboxed searches to execute...")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=False,
            args=["--disable-blink-features=AutomationControlled"]
        )
        
        context = await browser.new_context(
            viewport={"width": 1280, "height": 900},
            user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
        )
        
        await context.add_cookies([{"name": "auth_token", "value": X_AUTH_TOKEN, "domain": ".x.com", "path": "/"}])
        page = await context.new_page()

        for since_date, until_date in date_ranges:
            url_query = f"{BASE_QUERY} since:{since_date} until:{until_date}"
            search_url = f"https://x.com/search?q={url_query}&src=typed_query"
            
            print(f"\n🗓️ RECOVERY Search: {since_date} to {until_date}...")
            
            max_retries = 3
            attempt = 0
            chunk_success = False

            while attempt < max_retries and not chunk_success:
                attempt += 1
                try:
                    await page.goto(search_url, timeout=60000, wait_until="domcontentloaded")
                    await asyncio.sleep(4) # Slightly longer initial wait for recovery
                except Exception:
                    print(f"  -> ⚠️ Navigation timed out (Attempt {attempt}). Retrying...")
                    await asyncio.sleep(5)
                    continue
                
                # Check for explicit error states
                error_loc = page.locator('text="Something went wrong"')
                retry_btn = page.locator('[data-testid="empty_state_button_text"]')
                rate_limit = page.locator('text="Rate limit exceeded"')
                
                if await error_loc.count() > 0 or await retry_btn.count() > 0 or await rate_limit.count() > 0:
                    wait_time = 90 * attempt # Stricter cooldown for recovery mode
                    print(f"  -> 🛑 X blocked the request or rate limited. Cooling down for {wait_time} seconds...")
                    await asyncio.sleep(wait_time)
                    continue 

                # Wait for tweets with a much longer timeout (15 seconds) to counter throttling
                try:
                    await page.wait_for_selector('[data-testid="tweet"]', timeout=15000)
                    chunk_success = True 
                except Exception:
                    if await page.locator('text="Something went wrong"').count() == 0:
                        print("  -> Still no tweets found. If you know tweets exist here, your token might be soft-banned.")
                        chunk_success = True # Move on so we don't infinitely loop
                    continue

                if chunk_success:
                    for _ in range(2): 
                        tweets = await page.locator('[data-testid="tweet"]').all()
                        for tweet in tweets:
                            try:
                                text_loc = tweet.locator('[data-testid="tweetText"]')
                                tweet_text = await text_loc.inner_text() if await text_loc.count() > 0 else ""
                                
                                photo_loc = tweet.locator('[data-testid="tweetPhoto"] img')
                                if await photo_loc.count() > 0:
                                    image_url = await photo_loc.first.get_attribute('src')
                                    
                                    tweet_url = ""
                                    time_link = tweet.locator('a:has(time)')
                                    if await time_link.count() > 0:
                                        href = await time_link.first.get_attribute('href')
                                        if href:
                                            tweet_url = f"https://x.com{href}"
                                    
                                    if image_url and "media" in image_url and image_url not in seen_tweets:
                                        seen_tweets.add(image_url)
                                        scraped_data.append({
                                            "tweet_text": tweet_text,
                                            "image_url": image_url,
                                            "tweet_url": tweet_url
                                        })
                                        print(f"  ✅ [Total: {len(seen_tweets)}] Extracted: {tweet_text[:30].replace(chr(10), ' ')}...")
                            except Exception:
                                continue
                        
                        await page.mouse.wheel(0, 2000)
                        await asyncio.sleep(3)

            if not chunk_success:
                print(f"  -> ❌ Failed to fetch {since_date} to {until_date}. Stopping to prevent ban.")
                break 

            # Save incrementally after every successful chunk
            with open(JSON_FILE, "w", encoding="utf-8") as f:
                json.dump(scraped_data, f, indent=4)

        await context.close()
        await browser.close()
        
    return scraped_data

# Run the recovery!
data = await run_recovery_scraper()

print(f"\n🎉 RECOVERY COMPLETE. Total dataset now has {len(data)} tweets.")

📦 Loaded 113 previously scraped tweets. Ready to append...
Generated 8 recovery timeboxed searches to execute...

🗓️ RECOVERY Search: 2025-08-18 to 2025-09-17...
  -> Still no tweets found. If you know tweets exist here, your token might be soft-banned.

🗓️ RECOVERY Search: 2025-09-17 to 2025-10-17...
  -> Still no tweets found. If you know tweets exist here, your token might be soft-banned.

🗓️ RECOVERY Search: 2025-10-17 to 2025-11-16...
  ✅ [Total: 114] Extracted: Has RBI really announced 'new ...
  ✅ [Total: 115] Extracted:  Will retired Govt employees s...

🗓️ RECOVERY Search: 2025-11-16 to 2025-12-16...
  ✅ [Total: 116] Extracted:  Stay Alert   Claims are being...
  ✅ [Total: 117] Extracted: Have you received a voicemail,...
  ✅ [Total: 118] Extracted:  Will retired Govt employees s...

🗓️ RECOVERY Search: 2025-12-16 to 2026-01-15...
  ✅ [Total: 119] Extracted: Just click on the link & share...
  ✅ [Total: 120] Extracted: A #fake lucky draw is luring p...
  ✅ [Total: 121] Extracted: Did you also receive a message...
  ✅ [Total: 122] Extracted: इंस्टाग्राम अकाउंट ‘manjju.cho...
  ✅ [Total: 123] Extracted: RBI to stop ₹500 notes from AT...

🗓️ RECOVERY Search: 2026-01-15 to 2026-02-14...
  ✅ [Total: 124] Extracted: Is it true that your SBI YONO ...
  ✅ [Total: 125] Extracted: A Facebook advertisement claim...
  ✅ [Total: 126] Extracted: An approval letter claims to g...

🗓️ RECOVERY Search: 2026-02-14 to 2026-03-16...
  ✅ [Total: 127] Extracted: An Instagram advertisement cla...
  ✅ [Total: 128] Extracted: A letter circulating in the na...
  ✅ [Total: 129] Extracted: An approval letter claims to g...
  ✅ [Total: 130] Extracted: Chance to earn over ₹1,950,000...
  ✅ [Total: 131] Extracted: An email is circulating online...
  ✅ [Total: 132] Extracted: Did you also receive a message...

🗓️ RECOVERY Search: 2026-03-16 to 2026-04-08...
  ✅ [Total: 133] Extracted: A #fake lucky draw is luring p...
  ✅ [Total: 134] Extracted: Did you also receive a message...
  ✅ [Total: 135] Extracted:  Fake Investment Scam Using AI...
  ✅ [Total: 136] Extracted: Is it true that your SBI YONO ...
  ✅ [Total: 137] Extracted: An approval letter falsely cla...
  ✅ [Total: 138] Extracted: Chance to earn over ₹20,00,000...

🎉 RECOVERY COMPLETE. Total dataset now has 138 tweets.

In [13]:
import json
import os
import requests
import pandas as pd
from io import BytesIO
from PIL import Image
from pydantic import BaseModel, Field
from google import genai
from google.genai import types

# --- CONFIGURATION ---
GEMINI_API_KEY = "AIzaSyAdrydrEIrEc4Tu6_6jf3WuwQ-2iivWQsI" # <-- Paste your API key here
LOCAL_JSON_FILE = "raw_tweets_bulk.json"    # <-- Pointing to your new 112-tweet dataset!

# Initialize Gemini client
ai_client = genai.Client(api_key=GEMINI_API_KEY)

# --- NLP SCHEMA DEFINITION ---
# This forces the LLM to return data exactly in this structure
class MisinfoData(BaseModel):
    target_institution: str = Field(description="The bank or govt body being impersonated (e.g., SBI, RBI, Income Tax). If none, write 'Unknown'.")
    scam_vector: str = Field(description="How the scam is delivered: 'WhatsApp', 'SMS', 'Website', 'News Article', or 'Other'.")
    misinfo_type: str = Field(description="Categorize the scam: e.g., 'Account Block', 'Fake Scheme', 'Loan Fraud'.")
    core_claim: str = Field(description="A concise 1-sentence summary of the false claim.")
    extracted_text: str = Field(description="The readable text from the scam image, ignoring the red 'FAKE' watermarks.")

# --- PHASE 2 & 3: VISION & NLP PIPELINE ---
def process_tweet_content(tweet_text, image_url):
    try:
        # 1. Download the image into memory
        response = requests.get(image_url)
        response.raise_for_status()
        img = Image.open(BytesIO(response.content))
        
        # 2. Build the prompt
        prompt = f"""
        Analyze the attached image and the official tweet text from PIB Fact Check.
        The image contains financial misinformation with a 'FAKE' watermark over it.
        Read through the watermark and extract the details of the scam.
        
        Official Tweet Text: "{tweet_text}"
        """
        
        # 3. Call Gemini Multimodal with Structured Outputs
        result = ai_client.models.generate_content(
            model='gemini-2.5-flash',
            contents=[img, prompt],
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=MisinfoData,
                temperature=0.1 # Low temp to prevent hallucinations
            ),
        )
        return result.text
        
    except Exception as e:
        print(f"  -> Error processing image {image_url}: {e}")
        return None

# --- PHASE 4: EXECUTION & CSV EXPORT ---
def main():
    if not os.path.exists(LOCAL_JSON_FILE):
        print(f"❌ Error: Could not find {LOCAL_JSON_FILE}. Make sure it's in the same folder!")
        return

    # Load the data your bot just scraped
    print(f"Loading raw tweets from {LOCAL_JSON_FILE}...")
    with open(LOCAL_JSON_FILE, 'r', encoding='utf-8') as f:
        raw_tweets = json.load(f)
    
    if not raw_tweets:
        print("No tweets found in the JSON file. Exiting.")
        return

    processed_data = []
    
    print(f"\nProcessing {len(raw_tweets)} images and structuring data with Gemini...")
    for i, tweet in enumerate(raw_tweets):
        print(f"Processing image {i+1}/{len(raw_tweets)}...")
        
        # Pass the data to the LLM
        structured_json_str = process_tweet_content(tweet["tweet_text"], tweet["image_url"])
        
        if structured_json_str:
            try:
                extracted_info = json.loads(structured_json_str)
                
                # Merge original tweet data with extracted LLM data
                row = {
                    "Institution": extracted_info.get("target_institution", "Unknown"),
                    "Scam_Vector": extracted_info.get("scam_vector", "Unknown"),
                    "Misinfo_Type": extracted_info.get("misinfo_type", "Unknown"),
                    "Core_Claim": extracted_info.get("core_claim", ""),
                    "Original_Tweet": tweet["tweet_text"].replace('\n', ' '),
                    "Image_Text": extracted_info.get("extracted_text", "").replace('\n', ' '),
                    "Image_URL": tweet["image_url"]
                }
                processed_data.append(row)
            except json.JSONDecodeError:
                print(f"  -> Failed to parse JSON from Gemini for an image.")

    # Compile to CSV
    if processed_data:
        df = pd.DataFrame(processed_data)
        output_file = "pib_financial_factchecks.csv"
        df.to_csv(output_file, index=False, encoding='utf-8')
        print(f"\n✅ Success! Structured data saved to {output_file}")
        
        # Display the first few rows
        print("\nPreview of extracted data:")
        from IPython.display import display
        display(df[['Institution', 'Misinfo_Type', 'Core_Claim']].head())
    else:
        print("\n❌ No data successfully processed.")

if __name__ == "__main__":
    main()

Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed

Loading raw tweets from raw_tweets_bulk.json...

Processing 138 images and structuring data with Gemini...
Processing image 1/138...
Processing image 2/138...
Processing image 3/138...
Processing image 4/138...
Processing image 5/138...
Processing image 6/138...
Processing image 7/138...
Processing image 8/138...
Processing image 9/138...
Processing image 10/138...
Processing image 11/138...
Processing image 12/138...
Processing image 13/138...
Processing image 14/138...
Processing image 15/138...
Processing image 16/138...
Processing image 17/138...
Processing image 18/138...
Processing image 19/138...
Processing image 20/138...
Processing image 21/138...
Processing image 22/138...
Processing image 23/138...
Processing image 24/138...
Processing image 25/138...
Processing image 26/138...
Processing image 27/138...
Processing image 28/138...
Processing image 29/138...
Processing image 30/138...
Processing image 31/138...
Processing image 32/138...
Processing image 33/138...
Processing image 34/138...
Processing image 35/138...
Processing image 36/138...
Processing image 37/138...
Processing image 38/138...
Processing image 39/138...
Processing image 40/138...
Processing image 41/138...
Processing image 42/138...
Processing image 43/138...
Processing image 44/138...
Processing image 45/138...
Processing image 46/138...
Processing image 47/138...
Processing image 48/138...
Processing image 49/138...
Processing image 50/138...
Processing image 51/138...
Processing image 52/138...
Processing image 53/138...
Processing image 54/138...
Processing image 55/138...
Processing image 56/138...
Processing image 57/138...
Processing image 58/138...
Processing image 59/138...
Processing image 60/138...
Processing image 61/138...
Processing image 62/138...
Processing image 63/138...
Processing image 64/138...
Processing image 65/138...
Processing image 66/138...
Processing image 67/138...
Processing image 68/138...
Processing image 69/138...
Processing image 70/138...
Processing image 71/138...
Processing image 72/138...
Processing image 73/138...
Processing image 74/138...
Processing image 75/138...
Processing image 76/138...
Processing image 77/138...
Processing image 78/138...
Processing image 79/138...
Processing image 80/138...
Processing image 81/138...
Processing image 82/138...
Processing image 83/138...
Processing image 84/138...
Processing image 85/138...
Processing image 86/138...
Processing image 87/138...
Processing image 88/138...
Processing image 89/138...
Processing image 90/138...
Processing image 91/138...
Processing image 92/138...
Processing image 93/138...
Processing image 94/138...
Processing image 95/138...
Processing image 96/138...
Processing image 97/138...
Processing image 98/138...
Processing image 99/138...
Processing image 100/138...
Processing image 101/138...
Processing image 102/138...
  -> Failed to parse JSON from Gemini for an image.
Processing image 103/138...
Processing image 104/138...
Processing image 105/138...
Processing image 106/138...
Processing image 107/138...
Processing image 108/138...
Processing image 109/138...
Processing image 110/138...
Processing image 111/138...
Processing image 112/138...
Processing image 113/138...
Processing image 114/138...
Processing image 115/138...
Processing image 116/138...
Processing image 117/138...
Processing image 118/138...
Processing image 119/138...
Processing image 120/138...
Processing image 121/138...
Processing image 122/138...
Processing image 123/138...
Processing image 124/138...
Processing image 125/138...
Processing image 126/138...
Processing image 127/138...
Processing image 128/138...
Processing image 129/138...
Processing image 130/138...
Processing image 131/138...
Processing image 132/138...
Processing image 133/138...
Processing image 134/138...
Processing image 135/138...
Processing image 136/138...
Processing image 137/138...
Processing image 138/138...

✅ Success! Structured data saved to pib_financial_factchecks.csv

Preview of extracted data:

,Institution,Misinfo_Type,Core_Claim
0,India Post Payments Bank,Account Block,The customer's India Post Payments bank accoun...
1,RBI,Fake Currency Information,A ₹500 note should not be taken if the green s...
2,Indian Government,Loan Fraud,"A message claims that Rs. 20,55,000 is ready t..."
3,RBI,Account Block,The RBI Governor has announced that bank accou...
4,Pradhan Mantri Mudra Yojana,Loan Fraud,A letter falsely claims to approve a loan of ₹...

In [14]:
import pandas as pd
import json

# 1. Load your newly scraped JSON (which now has the tweet_urls)
with open("raw_tweets_bulk.json", "r", encoding="utf-8") as f:
    new_scraped_data = json.load(f)

# 2. Create a lookup dictionary mapping [image_url] -> [tweet_url]
url_map = {item['image_url']: item.get('tweet_url', 'URL Not Found') for item in new_scraped_data}

# 3. Load your existing structured CSV
df = pd.read_csv("pib_financial_factchecks.csv")

# 4. Map the tweet URLs into a new column based on the matching Image_URL
df["Tweet_URL"] = df["Image_URL"].map(url_map)

# 5. Reorder columns so the Tweet_URL is next to the Original_Tweet
cols = list(df.columns)
if 'Tweet_URL' in cols and 'Original_Tweet' in cols:
    cols.insert(cols.index('Original_Tweet') + 1, cols.pop(cols.index('Tweet_URL')))
    df = df[cols]

# 6. Save the final updated CSV
output_file = "pib_financial_factchecks_final.csv"
df.to_csv(output_file, index=False, encoding="utf-8")

print(f"✅ Success! Tweet links merged. Saved as '{output_file}' without re-running Gemini!")
display(df[['Institution', 'Misinfo_Type', 'Tweet_URL']].head())

✅ Success! Tweet links merged. Saved as 'pib_financial_factchecks_final.csv' without re-running Gemini!

,Institution,Misinfo_Type,Tweet_URL
0,India Post Payments Bank,Account Block,https://x.com/PIBFactCheck/status/167141937162...
1,RBI,Fake Currency Information,https://x.com/PIBFactCheck/status/167253922418...
2,Indian Government,Loan Fraud,https://x.com/PIBFactCheck/status/166819344012...
3,RBI,Account Block,https://x.com/PIBFactCheck/status/166930520964...
4,Pradhan Mantri Mudra Yojana,Loan Fraud,https://x.com/PIBFactCheck/status/167582507653...

In [6]:
import os

if os.path.exists("raw_tweets_bulk.json"):
    os.remove("raw_tweets_bulk.json")
    
if os.path.exists("scraper_checkpoint.txt"):
    os.remove("scraper_checkpoint.txt")
    
print("🗑️ Old cache cleared! You are ready for a clean run.")

🗑️ Old cache cleared! You are ready for a clean run.